modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="randomraid"
version="1.0.0"
displayName="Random Raid Spawn"
logoFile="examplemod.png"
credits=""
authors="Biggest_Xuan"
description='''
'''
[[dependencies.randomraid]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.randomraid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
